### PR TITLE
Correct password templates

### PR DESCRIPTION
**Pull request by bronger**
They are now in sync with
<https://gitlab.com/spectre.app/api/-/blob/main/c/spectre-types.c>.

### CODE REVIEW

**Review by emiljoha — COMMENTED** [review]
This looks exactly the same as in the source code you linked to.

This  is real bad, two out of 21 Long, one out of three Basic, and two out of three Pharse passwords do not match the reference implementation....

I am really uncomfortable to change is as it is a possibility that someone have generated a password with this that will not be recoverable after this change... But we also really need to follow the reference implementation. 

It could be possible to add a flag to set "patch level" or something to make the old buggy implementation available. It is still awful user experience if someone was bitten by this without knowing but it is at least somewhat recoverable.

Thoughts?

**Comment by emiljoha** [comment]
Thank you for taking the time to write a patch!

**Comment by bronger** [comment]
My clear advice: Change this ASAP! Anything else is worse. Besides, mpwalg – albeit very promising – is still a small project, thus, now is the time to do it.

I noticed it because I use not only mpwalg but also the app on Android. So, everyone having this scenario – or something similar – need this patch. Actually, the elegance of using MPW on different devices is one of the strongholds of this concept, because no data needs to be exchanged.

Of course, you could make the transition smoother for old users. Pointing to the problem prominently is surely very helpful, and rather simple.

If you want to go further, you could create a legacy password generator function next to the patched one, so that it’s easy to generate old and new – this would have made my tool much simpler that I used to find my affected accounts and migrate them.

The only alternative I see is to clearly state that you are not part of the MasterPasswordApp ecosystem but offer a similar, incompatible service.

**Review by emiljoha — APPROVED** [review]
> I do not use only mpwalg but also the app on Android.

This is how I use it as well, and I expect that is what most of the few people using this do. Together with the fact  that there are not that many users still is a really good argument to just do this.

> You could create a legacy password generator function next to the patched one, so that it’s easy to generate old and new – this would have made my tool much simpler that I used to find my affected accounts and migrate them.

Ouch... Sorry you had to go through that because I can not copy paste lists of strings. 

I will add a legacy function but lets move forward with fixing this.

**Pull request merged**
